server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ducapas
    username: postgres
    password: 1408
    driver-class-name: org.postgresql.Driver

flyway:
  url: jdbc:postgresql://localhost:5432/ducapas
  user: postgres
  password: 1408
  locations: classpath:db/migration
web:
  cors:
    allowed-origins: "http://localhost:8080"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"